### ISSUE TITLE
Seasonal candle get collected even tho the season end plz help fix this

### ISSUE THREAD

**Issue by Zartau** [thatskymod/Sky-CotL-Scripts#24] opened 2023-04-07 09:14 UTC
**Description:**

**To Reproduce:**
Steps to reproduce the behavior

**Expected behavior:**

**Actual behavior:**

**Screenshots:**

**Machine (please complete the following information):**
 - Device: 
 - OS: 
 - App(s) affected: 
 - Version: 

**Additional context:**

**Comment by thatskymod** [comment] 2023-04-07 16:20
If the issue pertains to AutoWax for Canvas, which is most commonly used, then the root cause is that seasonal wax remains in the form of plain data, even when its visibility is toggled off by a server-side switch. However, due to AutoWax lacking a concept of "seasons" and the closed-source nature of Sky, it is not possible to reliably differentiate between regular and seasonal wax, nor is it strictly necessary to do so. Consequently, this issue will not be addressed.

Please note that an issue template is provided, which all users are kindly requested to follow. The template clarifies that this repository is maintained exclusively by volunteers. As such, resolving issues in third-party software is beyond our scope.

If you believe that the issue with collection of seasonal wax is critical enough to be addressed, please head over to "[Credits & Resources](https://github.com/thatskymod/Sky-CotL-Scripts/tree/main/Canvas#credits--resources) " and get in touch with the scripts' or mods' respective authors.

For any other questions or concerns, please feel free to reach out. Thank you!

**Closed by thatskymod** 2023-04-07 16:20 UTC
