### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Azurev99** [thatskymod/Sky-CotL-Scripts#22] opened 2023-03-20 17:41 UTC
Im new to cheat please tutorial me how to use

**Comment by thatskymod** [comment] 2023-03-20 22:04
Hello @Azurev99,

did you have a look at the [Getting Started](https://github.com/thatskymod/Sky-CotL-Scripts/tree/main/Canvas#getting-started) section of Canvas? You'll find the first steps outlined there.

If you need any specific guidance, just let me know.

In any case, please be advised that cheating is bannable as per thatskygame's ToS, and I can not or will not en- or discourage you from doing it. The choice is yours.

**Comment by Azurev99** [comment] 2023-03-21 03:58
Nice thank you but i wanna ask you abt another script except autowax

**Comment by thatskymod** [comment] 2023-03-25 16:29
My apologies for the delayed response. As a result of some health challenges I've been facing recently, it took me longer than expected to get back to you.

I see you were asking about something else than Autowax. In that case, the [Available Libs](https://github.com/thatskymod/Sky-CotL-Scripts/tree/main/Canvas#available-libs) section is what you're looking for.

Quoting:

> ## Available Libs:
> - **Autowax** (aka. **libaw4c**) - A free helper program that collects the max number of daily available candles at the tap of a button, with extra features such WL, spirit collection, etc.
> - **reHell** or **libgxost** - Universal mod with many great features
> - **libRomanBeta** - Universal mod for Sky Beta
> - **libRomanDev** - Substitutes the Beta server with the Dev one (an even more private server, originally only for TGC devs)
> - **libfun** - Universal mod, but paid and poorly maintained

These libs can be found by browsing the repository -> Sky-CotL-Scripts -> Canvas -> Libs, and installed the same way as described previously.

For further knowledge, be sure to explore the [Credits & Resources](https://github.com/thatskymod/Sky-CotL-Scripts/tree/main/Canvas#credits--resources) section in the Readme.

Let me know if that's the answer you were looking for. If you have any further questions or concerns, feel free to reach out.

**Comment by Azurev99** [comment] 2023-03-25 16:34
Its ok just take care your health i mean how can i get another script except autowax.Thats what i want to ask

**Comment by thatskymod** [comment] 2023-03-26 19:04
Yes, of course there are other scripts except Autowax waiting to be discovered! One well-known free 'script' is libgxost, which you can grab [here](https://github.com/thatskymod/Sky-CotL-Scripts/blob/c02bde7448c8e4a14d683e60a276c63f57db9afd/Canvas/Libs/libgxost-1.1.7a.so).

It is a universal 'script' for Energy Boosting, Auto Run and Melt, Spells, Teleportation, and much more. It runs under the Canvas SML (**S**ky **M**odloader).

In case you prefer old-fashioned GameGuardian scripts, you can find them [here](https://github.com/thatskymod/Sky-CotL-Scripts/tree/main/LUA%20Scripts)  as well. However, note that these are a bit more complicated and may require some tinkering to work properly.

**Comment by Demonicbread** [comment] 2023-04-10 21:59
Hello! How do I download the file ?

**Comment by Demonicbread** [comment] 2023-04-10 22:22
Actually I managed to download some stuff, but the spirit shop and WL collector don't work :(

**Comment by SomebuddyElse7** [comment] 2023-04-15 02:56
Yes @Demonicbread im having the same issue and Im a bit new to using the Autowax lib and it seems I can't collect WL too. There is a empty text box that i think you are supposed to type in something but i don't know what it is so if anyone can help me too it would be great.

**Comment by thatskymod** [comment] 2023-04-15 15:31
How are you using it, @SomebuddyElse7? You might be doing it wrong.

Each winged light in Sky has its own unique codename or `id`. As a result, you need to specify the particular wing `id`s you wish to collect. To streamline this process, a wing list is available for you to copy and paste into the WL collector prompt.

Here it is: [220_wing_code_Sky.txt](https://raw.githubusercontent.com/thatskymod/Sky-CotL-Scripts/main/Canvas/Misc/220_wing_code_Sky.txt).

You can either copy this list to clipboard, or use your browser's download function to save it as a file and later load it into AutoWax.

**Comment by SomebuddyElse7** [comment] 2023-04-16 17:28
Yes that explains how to use it and thanks it works now. But im still having some problems with using the Spirit shop as it seems im not able to buy from the spirits like from the previous traveling spirits shown in the list.So im a bit confused that the purchase keeps getting denied is because those spirits are not available at the game in the moment or there's some other problems so if you could tell me it would be great (⁠^⁠^⁠).

**Comment by thatskymod** [comment] 2023-04-16 21:02
Duplicate of #5.

So basically, whenever you see "`denied`", the Sky server tells you that you tried to buy something that you weren't supposed to _(i.e. seasonal or event items outside their respective schedule)_. AutoWax can discover past or future limited items, but it cannot buy them due to restrictions out of our reach.

To verify AW's operability, you can start off by buying something simple first _(e.g. an emote upgrade from regular spirits)_, and the result should be one of the following: `ok`, `already` or `insuf`.

Let me know if that works!

**Comment by Azurev99** [comment] 2023-04-25 16:52
Ey how abt item show script, its gonna auto screenshot or manual but canavas and cheat icon will be hide when take a shot

**Comment by Demonicbread** [comment] 2023-04-25 17:56
@thatskymod I see, so if I'm right.
Ok=purchase successful
Already=you already have this item
Isuf=???
If you can please elaborate on "insuf".
Does it mean that I don't have enough candles/hearts?

**Comment by thatskymod** [comment] 2023-04-26 06:02
Yes @Demonicbread, you're absolutely correct!
- `already` indicates that you already own this item.
- `ok` signifies a successful purchase.
- `denied` means that purchasing this item is not allowed.

Consequently, `insuf` stands for **insufficient currency** (candles, hearts, ascended candles, etc).

**Comment by Demonicbread** [comment] 2023-04-26 10:40
Hmm, I see. What confuses me though is that I've gotten all the elder hairs and 1 mask, and I didn't lose any candles,hearts or AC.

**Comment by Gfyslls** [comment] 2023-04-26 17:41
Hello
Hope your health has been well, i would like to report a bug on smite. When using the "Candle Run" tab it will teleport me out the map or in the same place.

**Comment by thatskymod** [comment] 2023-04-30 10:57
> Hmm, I see. What confuses me though is that I've gotten all the elder hairs and 1 mask, and I didn't lose any candles,hearts or AC.

That is not possible, @Demonicbread. Whenever you successfully purchase something from the spirit shops, the cost is automatically deducted from your inventory. The effect may not be immediate, but it will be noticeable once you log in again or the next time Sky retrieves your currency.

It's worth noting that advanced nodes are dependent on their parent nodes. For example, to purchase level 4 of an emote, you must first have level 3, which in turn requires you to have levels 2 and 1. The only exception here is with Elder masks and hairs, which have no such restriction and can technically be purchased before the constellation is 100% completed.

**Comment by Demonicbread** [comment] 2023-04-30 13:28
Ah I see, thank you for the explanation!

**Comment by thatskymod** [comment] 2023-05-06 10:22
Thread deemed answered as of Mar 25, 2023 - find detailed response in [comment](https://github.com/thatskymod/Sky-CotL-Scripts/issues/22#issuecomment-1483863875).

Thanks for your understanding and feel free to submit a new issue for any other issues or concerns.

**Closed by thatskymod** 2023-05-06 10:22 UTC

**Comment by Demonicbread** [comment] 2023-05-06 11:58
@Gfyslls you should join the Dev's server, there you can submit bug reports
