### ISSUE TITLE
Need a current update for canvas

### ISSUE THREAD

**Issue by Thatskysimonsgame** [thatskymod/Sky-CotL-Scripts#3] opened 2022-12-01 06:25 UTC
need an updated canvas . In Beta it doesn't work at all, always force close.

**Comment by thatskymod** [comment] 2022-12-02 11:41
Hello,
make sure your Canvas is at version 1.2.7 (available in this repository) and that you removed any out-of-date mods. Libfun & libgxost have been causing problems lately - I'd suggest removing one by one to see which is the conflicting one.
If that doesn't help, screenshot me your Mod Manager and we'll figure it out!

**Comment by SamKK4** [comment] 2022-12-04 00:55
Hello there, I have been using the latest canvas app but none of the libs are working except for the aw4c.

**Comment by thatskymod** [comment] 2022-12-06 06:44
@SamKK4 Hello, mind telling what about the libs doesn't work?

P.S. The repository has been updated w/ new libs, pls give them a try (some old versions are kept solely for archival purposes, make sure you're always on the latest).

For Live, use:
• LibHellboy [2.1.8](tel:218)
• Libfun [1.1.9](tel:119)
• LibAW4C [1.2.0](tel:120)

For Beta, use:
• LibRomanBeta [1.1.2](tel:112)
• LibAW4C [1.2.0](tel:120)

**Comment by SamKK4** [comment] 2022-12-06 07:37
> @SamKK4 Hello, mind telling what about the libs doesn't work?
> 
> P.S. The repository has been updated w/ new libs, pls give them a try (some old versions are kept solely for archival purposes, make sure you're always on the latest).
> 
> For Live, use:
> • LibHellboy [2.1.8](tel:218)
> • Libfun [1.1.9](tel:119)
> • LibAW4C [1.2.0](tel:120)
> 
> For Beta, use:
> • LibRomanBeta [1.1.2](tel:112)
> • LibAW4C [1.2.0](tel:120)

Thanks for the new libs, I Tried them when they released and now they're working. 
          I don't have any issues with the new libs.

**Comment by thatskymod** [comment] 2022-12-07 09:59
Hello, can I just kindly confirm whether the issue is resolved? Be sure to write in if further help is required.
@Thatskysimonsgame

**Comment by SamKK4** [comment] 2022-12-07 10:54
Yes the issue has been resolved. Thank you

**Comment by thatskymod** [comment] 2022-12-09 11:43
The Hellboy project is discontinued due to the author being [personally busy](https://discord.com/channels/995809166419558630/995976676792078397/1046930636620968059). All its functions have been merged over to libgxost, which is a fusion of the now-dead hellboy + former gxost.

Take a look at the **/Canvas/Libs/** folder from this repository's tree. The two main working mods are:
• **libaw4c.1.2.0.so**: for candle & WL collection
• **libgxost-1.0.0.so**: for any other magic (teleportation, spells, read anon chat,...)

This issue will be marked solved for now, but don't hesitate to open a new one should you have any other questions. Cheers!

@xiytcotylon

**Closed by thatskymod** 2022-12-09 11:43 UTC
